name: MSTR_MobIgnore
main: ca.strendin.MSTR_MobIgnore.MSTR_MobIgnore
version: 0.1
author: Mark Strendin
description: Allows a player to frolic among enemies, unnoticed
permissions:
  MSTR_MobIgnore.ignoreall:   
   default: op
  MSTR_MobIgnore.ignorecreeper:   
   default: op   
commands:     